In [ ]:
s=np.array([2,4,6,8])
print(s)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
s=np.array([2,6,10,4])
print(s)

[ 2  6 10  4]


In [ ]:
np.reshape(s,(2,2))

array([[ 2,  4],
       [ 6, 10]])

In [24]:
s=np.arange(2,12)
print(s)

[ 2  3  4  5  6  7  8  9 10 11]


In [26]:
y=s.reshape(2,5)
print(y)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [30]:
z=np.transpose(y)
print(z)

[[ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]


In [31]:
y.transpose()

array([[ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [36]:
import numpy as np
a=np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [37]:

a[2:5]

array([4, 5, 6])

In [47]:
import numpy as np
x=np.arange(1,10).reshape[2;]
print(x)

ValueError: cannot reshape array of size 8 into shape (2,2)